# Generated by Django 4.2.5 on 2023-12-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(db_column='id_cliente', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fono', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_e', models.CharField(db_column='rut_e', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
            options={
                'db_table': 'Servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(db_column='id_atencion', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=200, null=True)),
                ('reserva', models.BooleanField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='app.cliente')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='app.servicio')),
                ('rut_e', models.ForeignKey(db_column='rut_e', on_delete=django.db.models.deletion.DO_NOTHING, to='app.empleado')),
            ],
            options={
                'db_table': 'Atencion',
                'managed': True,
            },
        ),
    ]
