# Generated by Django 4.2.5 on 2023-12-18 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='fecha_y_hora',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
